### ISSUE TITLE
Internal error in file lowering: java.lang.NoSuchMethodError with Kotlin 1.9.10

### ISSUE THREAD

**Issue by MarcelBreska** [realm/realm-kotlin#1500]
### How frequently does the bug occur?

Always

### Description

Kotlin version 1.9.10 build fails with error

### Stacktrace & log output

```shell
Details: Internal error in file lowering: java.lang.NoSuchMethodError: 'org.jetbrains.kotlin.name.Name org.jetbrains.kotlin.ir.expressions.IrPropertyReference.getReferencedName()'
	at io.realm.kotlin.compiler.IrUtilsKt.getLinkingObjectPropertyName(IrUtils.kt:594)
	at io.realm.kotlin.compiler.RealmModelSyntheticPropertiesGeneration$addSchemaMethodBody$1.invoke(RealmModelSyntheticPropertiesGeneration.kt:688)
	at io.realm.kotlin.compiler.RealmModelSyntheticPropertiesGeneration$addSchemaMethodBody$1.invoke(RealmModelSyntheticPropertiesGeneration.kt:463)
	at io.realm.kotlin.compiler.IrUtilsKt.blockBody(IrUtils.kt:127)
	at io.realm.kotlin.compiler.RealmModelSyntheticPropertiesGeneration.addSchemaMethodBody(RealmModelSyntheticPropertiesGeneration.kt:463)
	at io.realm.kotlin.compiler.RealmModelLowering.lower(RealmModelLoweringExtension.kt:113)
	at org.jetbrains.kotlin.backend.common.ClassLoweringVisitor.visitClass(Lower.kt:104)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitClass(IrElementVisitorVoid.kt:111)
	at org.jetbrains.kotlin.backend.common.ClassLoweringVisitor.visitClass(Lower.kt:95)
	at org.jetbrains.kotlin.backend.common.ClassLoweringVisitor.visitClass(Lower.kt:95)
	at org.jetbrains.kotlin.ir.declarations.IrClass.accept(IrClass.kt:73)
	at org.jetbrains.kotlin.ir.declarations.IrFile.acceptChildren(IrFile.kt:37)
	at org.jetbrains.kotlin.ir.visitors.IrVisitorsKt.acceptChildrenVoid(IrVisitors.kt:15)
	at org.jetbrains.kotlin.backend.common.ClassLoweringVisitor.visitElement(Lower.kt:99)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitPackageFragment(IrElementVisitorVoid.kt:190)
	at org.jetbrains.kotlin.backend.common.ClassLoweringVisitor.visitPackageFragment(Lower.kt:95)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitFile(IrElementVisitorVoid.kt:200)
	at org.jetbrains.kotlin.backend.common.ClassLoweringVisitor.visitFile(Lower.kt:95)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitFile(IrElementVisitorVoid.kt:198)
	at org.jetbrains.kotlin.backend.common.ClassLoweringVisitor.visitFile(Lower.kt:95)
	at org.jetbrains.kotlin.backend.common.ClassLoweringVisitor.visitFile(Lower.kt:95)
	at org.jetbrains.kotlin.ir.declarations.IrFile.accept(IrFile.kt:31)
	at org.jetbrains.kotlin.ir.visitors.IrVisitorsKt.acceptVoid(IrVisitors.kt:11)
	at org.jetbrains.kotlin.backend.common.LowerKt.runOnFilePostfix(Lower.kt:92)
	at io.realm.kotlin.compiler.RealmModelLowering.lower(RealmModelLoweringExtension.kt:59)
	at org.jetbrains.kotlin.backend.common.LowerKt.lower(Lower.kt:76)
	at io.realm.kotlin.compiler.RealmModelLoweringExtension.generate(RealmModelLoweringExtension.kt:48)
	at org.jetbrains.kotlin.backend.jvm.JvmIrCodegenFactory.convertToIr$lambda$1(JvmIrCodegenFactory.kt:222)
	at org.jetbrains.kotlin.psi2ir.Psi2IrTranslator.generateModuleFragment(Psi2IrTranslator.kt:107)
	at org.jetbrains.kotlin.backend.jvm.JvmIrCodegenFactory.convertToIr(JvmIrCodegenFactory.kt:255)
	at org.jetbrains.kotlin.backend.jvm.JvmIrCodegenFactory.convertToIr(JvmIrCodegenFactory.kt:59)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.convertToIr(KotlinToJVMBytecodeCompiler.kt:224)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:101)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli$default(KotlinToJVMBytecodeCompiler.kt:47)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:168)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:53)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:100)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:46)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:101)
	at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:460)
	at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:62)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.doCompile(IncrementalCompilerRunner.kt:476)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileImpl(IncrementalCompilerRunner.kt:399)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileNonIncrementally(IncrementalCompilerRunner.kt:280)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compile(IncrementalCompilerRunner.kt:124)
	at org.jetbrains.kotlin.daemon.CompileServiceImplBase.execIncrementalCompiler(CompileServiceImpl.kt:636)
	at org.jetbrains.kotlin.daemon.CompileServiceImplBase.access$execIncrementalCompiler(CompileServiceImpl.kt:101)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1598)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(Unknown Source)
	at java.rmi/sun.rmi.transport.Transport$1.run(Unknown Source)
	at java.rmi/sun.rmi.transport.Transport$1.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Unknown Source)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(Unknown Source)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(Unknown Source)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoSuchMethodError: 'org.jetbrains.kotlin.name.Name org.jetbrains.kotlin.ir.expressions.IrPropertyReference.getReferencedName()'
	... 65 more
```

### Can you reproduce the bug?

Always

### Reproduction Steps

Add backlink to RealmObject

### Version

1.10.2

### What Atlas App Services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

Compiletime

### Build environment

Android Studio version: Android Studio Giraffe | 2022.3.1 Patch 1
Android Build Tools version: 34
Gradle version:  8.1.1

**Comment by MarcelBreska** [comment]
Update: If I remove backlinks from my RealmObject, the code is compiling. The error is only occurring while using RealmObjects with backlinks.

For example: val user: RealmResults<User> by backlinks(User::posts)

**Comment by cmelchior** [comment]
Just to be 100% sure. Have you checked that both the Realm Gradle Plugin and the library dependency are using the same version? At least that is the common source of these kinds of errors.

**Comment by MarcelBreska** [comment]
Everything is running 1.10.2

id("io.realm.kotlin").version("1.10.2")
implementation("io.realm.kotlin:library-base:1.10.2")

**Comment by cmelchior** [comment]
Ah, wait. It looks like you are running into this issue: https://github.com/realm/realm-kotlin/issues/1469. We did a fix for this which should be available in 1.11.0: https://github.com/realm/realm-kotlin/blob/main/CHANGELOG.md#fixed-1

**Comment by MarcelBreska** [comment]
Ah perfect, it is working with 1.11.0. I thought 1.10.2 was the newest version. Thank you!

**Comment by maitriyogin** [comment]
Hi,
I'm getting this with 
id("io.realm.kotlin") version "1.12.0"
Multiplatform compose-plugin = "1.5.10"
kotlin = "1.9.20"

When I try and instantiate an App in a repository like:
`private val app: App = App.create(MONGODB_REALM_APP_ID)`


`Details: Internal error in file lowering: java.lang.NoSuchMethodError: 'org.jetbrains.kotlin.ir.expressions.IrConst org.jetbrains.kotlin.ir.interpreter.IrTreeBuildUtilsKt.toIrConstOrNull(java.lang.Object, org.jetbrains.kotlin.ir.types.IrType, int, int)'
	at io.realm.kotlin.compiler.SyncLowering$transformer$1.visitCall(SyncLoweringExtension.kt:150)`

I'd really love to get this working, if you have any insights I'd be eternally grateful.
/Stephen
