### ISSUE TITLE
Kotlin 1.6.20-RC Support

### ISSUE THREAD

**Issue by Reedyuk** [realm/realm-kotlin#720]
When using realm in a Kotlin Multiplatform project, im getting the following error:
```
Compilation failed: Back-end: Please report this problem https://kotl.in/issue
/Users/andrewreed/Documents/workspace/Mobile-Library/src/commonMain/kotlin/com/coolio/mp/storage/models/realm/Alias.kt:-1:-1
Details: Internal error in file lowering: java.lang.IllegalStateException: Cannot find io.realm.internal.interop.ClassInfo on platform Native (general).
```

The file in question is very simple so i dont think its related to the syntaxes used in it, but here it is:
```
package com.coolio.mp.storage.models.realm

import io.realm.RealmObject

class Alias : RealmObject {
    var stringValue: String = ""
}
```

Pretty sure something internal is going wrong with Kotlin and Realm, its probably more likely an issue with Kotlin 1.6.20 but i thought best to raise it here too.

**Comment by cmelchior** [comment]
Hi @Reedyuk Thank you for the report. That error looks similar to https://github.com/realm/realm-kotlin/issues/662. What version of the Realm SDK are you using?

**Comment by Reedyuk** [comment]
0.10.0

**Comment by nhachicha** [comment]
Hi @Reedyuk can you please share an example (or your Gradle files), I tried both on an Android and KMM project and both works with `1.6.20-RC2`

**Comment by Reedyuk** [comment]
currently on 1.6.10 for now, ive not got chance to reproduce again.
